Select Top 20 *  from customer;

-- Q1- What is the total revenue generated by male vs female customers ? -- 

select gender, SUM(purchase_amount) as revenue
from customer
group by gender;

-- Q2- Which customers used a discount but still spent more than the average purchase amount?--

Select customer_id, discount_applied,purchase_amount from customer
Where discount_applied='Yes' and purchase_amount >= (Select AVG(Purchase_amount) from customer);

--Q3- Which are the top 5 products with the highest average review rating?-

Select Top 5 item_purchased, Category , Round(AVG(review_rating),2) as "Average Product Rating" from customer
group by item_purchased, Category
order by Avg(review_rating) DESC;

--Q4- Compare the Average Product Amounts between Standard and Express shipping?

Select shipping_type, AVG(purchase_amount) as "Average Purchase Amount" from customer
where shipping_type in ('Standard' , 'Express')
group by shipping_type;

--Q5- Do subscribed Customers spend more ? Compare Average spend and Total revenue between subscribers and non-subscribers?

Select subscription_status, Count(Customer_id) as "Total Customers",
AVG(purchase_amount) as "Average Spend" , Sum(Purchase_amount) as "Total Revenue" from customer
group by subscription_status
order by "Total Revenue", "Average Spend" DESC;

--Q6- Which 5 products have the highest percentage of purchase with discounts applied?

Select Top 5 item_purchased, Category,
Concat((Sum(CASE When discount_applied = 'Yes' Then 1 Else 0 End)*100/Count(*)),'%') as Discount_rate
from Customer
group by item_purchased, Category
order by Discount_rate DESC;

--Q7- Segment Customers into New, Returning, and Loyal based on their Total number of previous purchases, 
--and show the count of each segment?

With Customer_type as (
Select customer_id, previous_purchases,
Case when previous_purchases = 1 then 'New'
	 when previous_purchases Between 2 and 10 then 'Returning' 
	 Else 'Loyal'
	 End as Customer_Segment from Customer)
Select Customer_segment, Count(*) as 'Number of Customers' from Customer_type
group by Customer_Segment
order by 'Number of Customers' Desc;

--Q8- What are the Top 3 most purchased products within each category?

With item_counts as (
Select category, item_purchased, Count(Customer_id) as total_orders,
ROW_NUMBER() over(Partition by category order by count(Customer_id)DESC) as item_rank from Customer
group by category, item_purchased)

Select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <=3;

